version: '3.8'

services:
  # LinkedIn API Service
  api:
    build: .
    container_name: linkedin-api
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - CHROME_BIN=/usr/bin/chromium
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - DISPLAY=:99
      - DB_HOST=${DB_HOST:-linkedin-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-linkedin}
    shm_size: '2g'
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    depends_on:
      - linkedin-db
    profiles:
      - production
    networks:
      - linkedin-network

  # n8n Workflow Automation Service
  n8n:
    build:
      dockerfile: ./Dockerfile.patched.n8n
    container_name: n8n
    ports:
      - "${N8N_PORT}:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true # Allow AI nodes to use custom linkedin nodes as tool
      - N8N_TRUST_PROXY=${N8N_PROXY:-}
      - NODE_ENV=production
      - NODE_FUNCTION_ALLOW_EXTERNAL=${EXTERNAL:-'uuid,cheerio'}
      - WEBHOOK_URL=${N8N_WEBHOOK_URL:-${N8N_PROTOCOL:-http}://${N8N_HOST:-localhost}:5678/}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/Paris}
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_custom_nodes:/home/node/.n8n/custom
    profiles:
      - development
      - production
    restart: unless-stopped
    networks:
      - linkedin-network

  # PostgreSQL Database Service
  linkedin-db:
    image: postgres:15
    container_name: linkedin-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkedin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    profiles:
      - production
      - development
    networks:
      - linkedin-network

volumes:
  n8n_data:
    driver: local
  postgres_data:
    driver: local

networks:
  linkedin-network:
    driver: bridge

